In [12]:
import pandas as pd
sdata = pd.read_csv("final-clean-sentiment_class.csv")
sdata.drop('Unnamed: 0', axis=1, inplace=True)
sdata.clean_tweet4 = sdata.clean_tweet4.astype(str)
sdata.head(2)

,date,hashtags,username,nlikes,nreplies,nretweets,search,clean_tweet4,year,month,check,sentiment,sentiment_class
0,12/29/2019 13:54,[],JesusDailyTwits,1,0,0,depression,best depression killer worshipping jesus try v...,2019,12,mh,-0.2960,Negative
1,12/29/2019 12:47,[],Aluvrendar,67,3,6,depression,hope blessings majlis depression never return ...,2019,12,mh,0.6149,Very Positive

In [62]:
# List from youtube group
mental_health_keywords = ['depression', 'mental', 'illness', 'unalive', 'social', 'anxiety', 'loneliness', 'stress', 'lonely', 'isolation', 'suicide', 
                            'abuse', 'death', 'post', 'traumatic', 'stress', 'disorder', 'no', 'motivation', 'therapy', 'trauma', 'counselling', 'mood', 
                            'disorder', 'mood', 'swings', 'mental', 'health', 'angst', 'emotion', 'phobia', 'addiction', 'stigma', 'self-harm', 'neurosis', 
                            'abuse', 'disorder', 'dependence', 'socialize', 'help', 'dead', 'melancholia', 'dysthemia', 'tired', 'trapped', 'paranoia', 
                            'overwhelmed', 'irritable', 'bipolar', 'psychologist', 'well-being', 'imh', 'sos', 'counsellor', 'toxic']
def check_mh(text):
    return any(word in text for word in mental_health_keywords)

covid_list = ['covid', 'coronavirus', 'covid-19', 'pandemic']
def check_cl(text):
    return any(word in text for word in covid_list)
    
sg_list = ['singapore', 'singaporean','sg']
def check_sg(text):
    return any(word in text for word in sg_list)

In [57]:
sdata['check_mental_health'] = sdata.clean_tweet4.apply(lambda x: check_mh(x))
sdata['check_covid'] = sdata.clean_tweet4.apply(lambda x: check_cl(x))
sdata['check_sg'] = sdata.clean_tweet4.apply(lambda x: check_sg(x))

In [58]:
sdata['check_mental_health'].value_counts()

True     37823
False    25541
Name: check_mental_health, dtype: int64

In [59]:
sdata['check_covid'].value_counts()

False    55690
True      7674
Name: check_covid, dtype: int64

In [60]:
sdata['check_sg'].value_counts()

False    55652
True      7712
Name: check_sg, dtype: int64

In [72]:
relevant_list = [sdata.check_mental_health[i] and sdata.check_covid[i] and sdata.check_sg[i] for i in range(len(sdata))]
sum(relevant_list)

475

In [ ]:
sdata["relevance"] = relevant_list

In [79]:
l = sdata[sdata.relevance == True]
l

,date,hashtags,username,nlikes,nreplies,nretweets,search,clean_tweet4,year,month,check,sentiment,sentiment_class,check_mental_health,check_covid,check_sg,relevance
13559,4/4/2020 20:59,"['daddysgurl', 'myxvjmainethisapril']",lili_eyebags,0,0,0,stress,relax muna stress brought covid watch daddysgu...,2020,4,mh,0.0258,Neutral,True,True,True,True
13593,3/21/2020 21:45,"['daddysgurl', 'mainemendoza']",lili_eyebags,1,0,3,stress,thank team dg pang alis ng stress dulot ng cov...,2020,3,mh,-0.0772,Neutral,True,True,True,True
13594,3/21/2020 21:06,"['daddysgurl', 'mainemendoza']",DorrisRivero,0,0,1,stress,stay home manood ng daddysgurl iwas sa stress ...,2020,3,mh,-0.4215,Negative,True,True,True,True
13610,3/15/2020 18:01,"['wheninsg', 'latergram']",feanneperez,2,0,0,stress,much covid stress go back sesame street anybod...,2020,3,mh,-0.4215,Negative,True,True,True,True
13970,3/28/2020 20:18,['coronavirussingapore'],rockydotsg,0,0,0,lonely,lonely merlion coronavirussingapore,2020,3,mh,-0.3612,Negative,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62474,7/1/2021 12:25,[],GlennEconomist,2,0,1,new normal,science human ingenuity eventually prevail cov...,2021,7,pd,0.0000,Neutral,True,True,True,True
62482,6/30/2021 15:54,"['queensland', 'covid19', 'singapore', 'auspol...",jikon,0,0,0,new normal,queensland losing plot local cases covid singa...,2021,6,pd,-0.3818,Negative,True,True,True,True
62500,5/15/2021 15:02,[],_rodahidup,0,0,1,new normal,focus tackling covid targeted measures new nor...,2021,5,pd,0.0000,Neutral,True,True,True,True
63106,6/13/2021 23:30,['strides4snowleopards'],torvaanser,29,1,6,heightened alert,last day heightened alert measures singapore a...,2021,6,pd,0.5994,Positve,True,True,True,True
63119,6/30/2021 15:47,"['covid19', 'covid19']",maximos62,2,1,0,stay home notice,singapore june preliminarily confirmation new ...,2021,6,pd,-0.3182,Negative,True,True,True,True

In [80]:
sdata.to_csv("final_relevance_check.csv")